# -*- coding: utf-8 -*-
# This line defines the encoding standard used for the Python file

"""Linear_Regession_part2.ipynb
This is the name of the original Jupyter Notebook file
Automatically generated by Google Colab
"""

# Link to the original Colab notebook where this code was created
# Original file is located at:
# https://colab.research.google.com/drive/1tO3Gutm7KIfVO_I6hzGIE4KRoIdo5krd

# Importing the wine dataset from sklearn
from sklearn.datasets import load_wine

# Importing pandas for data manipulation
import pandas as pd

# Importing numpy for numerical operations
import numpy as np

# Importing matplotlib for visualization
import matplotlib.pyplot as plt

# Loading the wine dataset into a variable
wine = load_wine()

# Printing the complete dataset structure (data, target, feature names, etc.)
print(wine)

# Printing only the feature data (independent variables)
print(wine.data)

# Assigning feature values to x (independent variables)
x = wine.data

# Assigning target values to y (dependent variable)
y = wine.target

# Importing function to split data into training and testing sets
from sklearn.model_selection import train_test_split

# Splitting data into 70% training and 30% testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

# Importing Linear Regression model from sklearn
from sklearn.linear_model import LinearRegression

# Creating an instance of the Linear Regression model
model = LinearRegression()

# Training the model using training data
Reg = model.fit(x_train, y_train)

# Evaluating the model using R² score on test data
Reg.score(x_test, y_test)


# THE BELOW CODE IS OPTIONAL
# It is not required because Reg.score() already calculates R² score

# Importing mean squared error metric
#from sklearn.metrics import mean_squared_error

# Importing R² score metric
#from sklearn.metrics import r2_score

# Predicting output values for test data
#y_pred = Reg.predict(x_test)

# Calculating mean squared error
#mse = mean_squared_error(y_test, y_pred)

# Calculating R² score manually
#r2 = r2_score(y_test, y_pred)

# Printing the R² score
#print(r2)
